apiVersion: redskyops.dev/v1alpha1
kind: Experiment
metadata:
  name: rally-helm-jvm
spec:
  budget: 160
  parameters:
  - name: data_memory
    min: 2000
    max: 8000
  - name: data_cpu
    min: 500
    max: 6000
  - name: data_replicas
    min: 1
    max: 3
  - name: data_heap_percent
    min: 20
    max: 80
  - name: client_memory
    min: 2000
    max: 8000
  - name: client_cpu
    min: 500
    max: 6000
  - name: client_replicas
    min: 1
    max: 3
  - name: client_heap_percent
    min: 20
    max: 80
  metrics:
  - name: duration
    minimize: true
    query: "{{duration .StartTime .CompletionTime}}"
  - name: cost
    minimize: true
    type: pods
    # Note that these cost weights are specific to GKE and represent $22/month/cpu and $3/month/GB
    query: '{{resourceRequests .Pods "cpu=0.022,memory=0.000000000003"}}'
    selector:
      matchLabels:
        app: elasticsearch
  patches:
  - targetRef:
      kind: StatefulSet
      apiVersion: apps/v1
      name: elasticsearch-master
    patch: ""
  - targetRef:
      kind: Deployment
      apiVersion: apps/v1
      name: elasticsearch-client
    patch: |
      spec:
        replicas: {{ .Values.client_replicas }}
        template:
          spec:
            containers:
            - name: elasticsearch
              env:
              - name: ES_JAVA_OPTS
                value: "-Djava.net.preferIPv4Stack=true -Xms{{ percent .Values.client_memory .Values.client_heap_percent }}m -Xmx{{ percent .Values.client_memory .Values.client_heap_percent }}m"
              resources:
                limits:
                  cpu: "{{ .Values.client_cpu }}m"
                  memory: "{{ .Values.client_memory }}Mi"
                requests:
                  cpu: "{{ .Values.client_cpu }}m"
                  memory: "{{ .Values.client_memory }}Mi"
  - targetRef:
      kind: StatefulSet
      apiVersion: apps/v1
      name: elasticsearch-data
    patch: |
      spec:
        replicas: {{ .Values.data_replicas }}
        template:
          spec:
            containers:
            - name: elasticsearch
              env:
              - name: ES_JAVA_OPTS
                value: "-Djava.net.preferIPv4Stack=true -Xms{{ percent .Values.data_memory .Values.data_heap_percent }}m -Xmx{{ percent .Values.data_memory .Values.data_heap_percent }}m"
              resources:
                limits:
                  cpu: "{{ .Values.data_cpu }}m"
                  memory: "{{ .Values.data_memory }}Mi"
                requests:
                  cpu: "{{ .Values.data_cpu }}m"
                  memory: "{{ .Values.data_memory }}Mi"
  template: # trial
    spec:
      setupTasks:
      - name: elasticsearch
        helmChart: stable/elasticsearch
        helmChartVersion: "1.31.1"
        helmValues:
        - name: cluster.name
          value: rally-demo
        - name: client.replicas
          value: "{{ .Values.client_replicas }}"
        - name: client.resources.limits.cpu
          value: "{{ .Values.client_cpu }}m"
        - name: client.resources.limits.memory
          value: "{{ .Values.client_memory }}Mi"
        - name: client.resources.requests.cpu
          value: "{{ .Values.client_cpu }}m"
        - name: client.resources.requests.memory
          value: "{{ .Values.client_memory }}Mi"
        - name: client.heapSize
          value: "{{ percent .Values.client_memory .Values.client_heap_percent }}m"
        - name: data.terminationGracePeriodSeconds
          value: "5"
        - name: data.podManagementPolicy
          value: Parallel
        - name: data.replicas
          value: "{{ .Values.data_replicas }}"
        - name: data.resources.limits.cpu
          value: "{{ .Values.data_cpu }}m"
        - name: data.resources.limits.memory
          value: "{{ .Values.data_memory }}Mi"
        - name: data.resources.requests.cpu
          value: "{{ .Values.data_cpu }}m"
        - name: data.resources.requests.memory
          value: "{{ .Values.data_memory }}Mi"
        - name: data.heapSize
          value: "{{ percent .Values.data_memory .Values.data_heap_percent }}m"
      setupServiceAccountName: redsky
      ttlSecondsAfterFinished: 1800
      template: # job
        spec:
          template: # pod
            spec:
              activeDeadlineSeconds: 1800
              containers:
              - image: elastic/rally:1.3.0
                name: rally
                args: ["--track=geopoint",
                       "--target-hosts=elasticsearch-client",
                       "--pipeline=benchmark-only",
                       "--challenge=append-fast-with-conflicts",
                       "--track-params=ingest_percentage:50"]
                volumeMounts:
                  - name: config
                    mountPath: /rally/.rally/rally.ini
                    subPath: rally-config
              volumes:
                - name: config
                  configMap:
                    name: rally-ini
