apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    app: voting-app
    component: voting-service
spec:
  ports:
  - port: 80
  selector:
    app: voting-app
    component: voting-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-service
  labels:
    app: voting-app
    component: voting-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voting-app
      component: voting-service
  strategy:
    type: Recreate
  template:
    metadata:
      name: voting-service
      labels:
        app: voting-app
        component: voting-service
    spec:
      containers:
      - name: voting-service
        image: dockersamples/examplevotingapp_vote
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 2000Mi
            cpu: 1.0
          requests:
            memory: 2000Mi
            cpu: 1.0
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
