---
# Source: prometheus/templates/configmaps/server.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prometheus
  name: prometheus-server
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      scrape_timeout: 3s
    scrape_configs:
    - job_name: kubernetes-cadvisor
      scheme: https
      metrics_path: /metrics/cadvisor
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      metric_relabel_configs:
      # We only consume the following metrics, so let's drop everything else
      - regex: ^container_cpu_usage_seconds_total|container_memory_max_usage_bytes$
        source_labels: [ __name__ ]
        action: keep
      # Drop labels we dont care about
      - regex: ^container|image|pod|namespace$
        action: labelkeep
    - job_name: kube-state-metrics
      scheme: http
      static_configs:
      - targets:
        - localhost:8080
      metric_relabel_configs:
      # We only consume the following metrics, so let's drop everything else
      - regex: ^kube_pod_container_resource_requests_cpu_cores|kube_pod_labels|kube_pod_container_resource_requests_memory_bytes$
        source_labels: [ __name__ ]
        action: keep
      # Drop labels we dont care about
      - regex: ^beta_kubernetes_io_arch$
        action: labeldrop
      - regex: ^kubernetes_io_arch$
        action: labeldrop
      - regex: ^beta_kubernetes_io_os$
        action: labeldrop
      - regex: ^kubernetes_io_os$
        action: labeldrop
      - regex: ^job$
        action: labeldrop
      - regex: ^instance$
        action: labeldrop
      - regex: ^node$
        action: labeldrop
    - job_name: prometheus-pushgateway
      honor_labels: true
      scheme: http
      static_configs:
      - targets:
        - localhost:9091
