# redskyImage is the image name (without tag) of the Red Sky Controller
redskyImage: "IMG"
# redskyTag sets the tag (application version) of the Red Sky Controller (for a chart release, it is preferable to only vary the patch level of this semver)
redskyTag: "TAG"
# redskyImagePullPolicy is the pull policy to apply to the Red Sky Controller image
redskyImagePullPolicy: "PULL_POLICY"

# remoteServer is used to configure a Red Sky API remote server
remoteServer:
  # enabled determines if the controller configuration secret should be generated or not
  enabled: false

  # identifier is the server identifier of the Red Sky API
  identifier: "https://api.carbonrelay.io/v1/"
  # issuer is the identifier of the Red Sky API authorization server
  issuer: "https://auth.carbonrelay.io/"
  # clientID is the unique client identifier assigned to the controller
  clientID: ""
  # clientSecret is the secret used to authenticate the controller
  clientSecret: ""

# rbac allows for customization of the RBAC related resources
rbac:
  # create specifies whether RBAC resources should be created
  create: true
  # bootstrapPermissions specifies whether the default bootstrap permissions should be included (requires create to also be true)
  bootstrapPermissions: true
  # extraPermissions specifies whether the extra permissions should be included (requires bootstrapPermissions to also be true)
  extraPermissions: false
